workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'

# variables:
#   IMAGE_OPENJDK_GRADLE: gradle:7.6.1-jdk17-alpine
#   IMAGE_OPENJDK: openjdk:17-alpine
variables:
  GRADLE_OPTS: "-Dorg.gradle.caching=true -Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  DOCKER_HOST: tcp://localhost:2375/

image: openjdk:17-alpine
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .gradlew/

stages:
  - test
  - build
  - deploy

build:
  image: docker
  stage: build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  allow_failure: true
  before_script:
    - cd backend/mmart/src/main/resources
    - echo $SPRINGBOOT_PROPS >> "application.properties"
    - cat application.properties
    - ls -al
    - cd ../../../
    - chmod +x gradlew
    - docker login -u teqteqteqteq -p $DOCKERHUB_PW
  script:
    - echo "Compiling the code..."
    - ./gradlew clean build -x test
  after_script:
    - echo "Building Docker Image..."
    - docker build -t teqteqteqteq/red-limo-backend:latest .
    - echo "Publishing Docker Image..."
    - docker push teqteqteqteq/red-limo-backend:latest

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  services:
    - docker:stable-dind
  allow_failure: true
  before_script:
    - docker login -u teqteqteqteq -p $DOCKERHUB_PW
  script:
    - kubectl apply -f k8s/deployment.yaml
