stages:  
  - test        # List of stages for jobs, and their order of execution
  - build
  - deploy

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: openjdk:11-jre-alpine
  script:
    - ./gradlew test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: gradle:7.6.1-jdk11-alpine
  script:
    - gradle --version
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
