workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'

# variables:
#   IMAGE_OPENJDK_GRADLE: gradle:7.6.1-jdk17-alpine
#   IMAGE_OPENJDK: openjdk:17-alpine
# variables:
#   GRADLE_OPTS: "-Dorg.gradle.caching=true -Dorg.gradle.daemon=false"
#   GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
#   DOCKER_HOST: tcp://docker:2375/

# image: openjdk:17-alpine
# cache:
#   key: $CI_COMMIT_REF_SLUG
#   paths:
#     - .gradlew/

stages:
  - test
  - build
  - deploy

build:
  image: openjdk:17-alpine
  stage: build
  allow_failure: true
  before_script:
    - cd backend/mmart/src/main/resources
    - echo $SPRINGBOOT_PROPS >> "application.properties"
    - cat application.properties
    - ls -al
    - cd ../../../
    - chmod +x gradlew
  script:
    - echo "Compiling the code..."
    - ./gradlew clean build -x test

package:
  image: docker:stable-dind
  stage: build
  allow_failure: true
  script:
    - docker --version
    - systemctl --user start docker
    - docker build -t teqteqteqteq/red-limo-backend backend/mmart/

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  allow_failure: true
  script:
    - kubectl apply -f k8s/deployment.yaml
