workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'master'

variables:
  IMAGE_OPENJDK_GRADLE: gradle:7.6.1-jdk17-alpine
  IMAGE_OPENJDK: openjdk:17-alpine

stages:
  - test
  - build
  - package
  - deploy

clean:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  before_script:
  - cd backend/mmart
  - chmod +x gradlew
  script:
    - echo "Cleaning leftovers from previous builds"
    - ./gradlew clean

build:
  image: $IMAGE_OPENJDK
  stage: build
  needs:
    - job: clean
  before_script:
  - cd backend/mmart
  - chmod +x gradlew
  script:
    - echo "Compiling the code..."
    - ./gradlew build -x test
  artifacts:
    name: app.jar
    paths:
      - backend/mmart/build/libs/mmart-0.0.1-SNAPSHOT.jar

package:
  stage: package
  before_script:
    - cd backend/mmart
    - docker login -u teqteqteqteq -p Kty960626!
  script:
    - echo "Building Docker Image..."
    - docker build -t teqteqteqteq/red-limo-backend:latest .
  after_script:
    - echo "Publishing Docker Image..."
    - docker push teqteqteqteq/red-limo-backend:latest
