apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-depl
  labels:
    app: analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
      - name: analysis
        image: teqteqteqteq/red-limo-analysis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "125m"
          limits:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-lb
spec:
  selector:
    app: analysis
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analysis-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analysis-depl
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50