apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-depl
  labels:
    app: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: teqteqteqteq/red-limo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     cpu: "125m"
        #   limits:
        #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-lb
spec:
  selector:
    app: springboot
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
