apiVersion: rbac.authorization.k8s.io/v1
kind: Role       
metadata:
  namespace: gitlab
  name: gitlab-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]