apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: gitlab
  name: gitlab-rb
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: gitlab
roleRef:
  kind: Role 
  name: gitlab-role
  apiGroup: rbac.authorization.k8s.io