services:
  database:
    container_name: mysql
    image: mysql:8-oracle
    ports:
      - 4444:3306
    environment:
      MYSQL_ROOT_PASSWORD: red-limo
      MYSQL_DATABASE: red-limo-db
      TZ: "Asia/Seoul"
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
      - conf:/etc/mysql/conf.d

  cache_database:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 8888:6379
    environment:
      TZ: "Asia/Seoul"
    restart: unless-stopped
    volumes:
      - cache:/data
    
  backend:
    restart: on-failure
    ports:
      - 8090:8080
    depends_on:
      - database
      - cache_database
    container_name: springboot
    image: red-limo-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/red-limo-db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: red-limo
      TZ: "Asia/Seoul"

  sentiment-analysis:
    container_name: sentiment_analysis_container
    build:
      context: ../../ai/sentiment_analysis
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 1695:80

volumes:
  data:
  cache:
  conf: